/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calendar.event.booking;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalTime;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;
import static org.junit.jupiter.api.Assertions.*;

class TimeSlotTest {
    @Nested
    class CommonTimeSlot {
        @Test
        void returnsNullWhenSlotsDontCoincideAtAll() {
            TimeSlot timeSlot = new TimeSlot(LocalTime.parse("10:00"), LocalTime.parse("11:00"));
            TimeSlot anotherTimeSlot = new TimeSlot(LocalTime.parse("11:00"), LocalTime.parse("12:00"));

            TimeSlot common = timeSlot.common(anotherTimeSlot);

            assertThat(common, is(nullValue()));
        }

    }
}
