/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calendar.event.booking;

import java.time.Duration;
import java.time.LocalTime;

public class TimeSlot {
    private final LocalTime start;
    private final LocalTime end;

    TimeSlot(LocalTime start, LocalTime end) {
        this.start = start;
        this.end = end;
    }

    public TimeSlot common(TimeSlot anotherTimeSlot) {
        return null;
    }
}
